version: '3.8'

networks:
  app_estudo2:
    name: app_estudo2
    external: true

services:
  nginx:
    image: crmsolucoes/nginx-stable-alpine:latest
    container_name: app_estudo2_nginx
    hostname: app_estudo2_nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_estudo2

  php:
    image: crmsolucoes/php-fpm-8.2:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - app_estudo2